### ISSUE TITLE
XpAppCompatCheckedTextView doesn't seem to work on API level 19

### ISSUE THREAD

**Issue by hckr** [consp1racy/android-commons#3]
I use the following XML code for elements of a RecyclerView. The advertised support for tint doesn't seem to work for me, unfortunately.

```
<android.support.v7.widget.XpAppCompatCheckedTextView
        android:id="@+id/todoItem"
        android:checkMark="?android:attr/textCheckMark"
        android:checkMarkTint="?android:attr/textCheckMark"
        android:drawableLeft="?android:attr/textCheckMark"
        android:drawableTint="@color/niceBlue"
        (...) />
```

Android 9 / API 28 – works as it should:
![checkedtextview_tint_api_28_android_9](https://user-images.githubusercontent.com/1078650/54037209-e0580500-41bd-11e9-9a2a-1d59c53bb378.png)

Android 4.4.2 / API 19 – doesn't work:
![checkedtextview_tint_api_19_android_4 4 2](https://user-images.githubusercontent.com/1078650/54037268-041b4b00-41be-11e9-8e2c-08baabf89959.png)

**Comment by consp1racy** [comment]
Thanks for reporting.

You need to use `app:drawableTint` instead of `android:drawableTint`. That will take care of tge compound drawables.

As for `checkMark`, I've never seen it before. I'll have to investigate.

**Comment by consp1racy** [comment]
I can implement support for tinting `checkMark` but ultimately the `appcompat-extras` library isn't built to last. It has things that are missing from appcompat.

The goal is to make AppCompat have the things we need in the first place so visit the [issue tracker](https://issuetracker.google.com/issues/new?component=460343) and leave a bug report there that tinting check mark in `AppCompatCheckedTextView` isn't working. Provide a sample app source and screenshots.

Check this out:

> ## Version 1.1.0-alpha01
> December 3, 2018
> 
> ### New features
> 
> * AppCompatTextView now supports `app:drawableLeftCompat`, `app:drawableTopCompat`, `app:drawableRightCompat`, `app:drawableBottomCompat`, `app:drawableStartCompat` and `app:drawableEndCompat` compound drawables, supporting backported drawable types such as `VectorDrawableCompat`.
> 
> * `AppCompatCheckBox` and `AppCompatRadioButton`’s default drawables now animate check state changes.

Source: https://developer.android.com/jetpack/androidx/releases/appcompat#1.1.0-alpha01

**Comment by consp1racy** [comment]
In commit 5737559f6b1a025674496c1d79e9c86666b14da5 you can use the following attributes on a `XpAppCompatCheckedTextView`:

* `app:checkMark` - support for vector drawables below Lollipop
* `app:checkMarkTint`
* `app:checkMarkTintMode`

**Comment by hckr** [comment]
Thanks for the implementation.
